# Generated by Django 5.0.7 on 2026-02-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("accuracy", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("korean_sentence", models.CharField(max_length=255)),
                ("north_korean_sentence", models.CharField(max_length=255)),
                ("is_called", models.BooleanField(default=False)),
                ("is_correct", models.BooleanField(default=False)),
                ("is_collect", models.BooleanField(default=False)),
                ("accuracy", models.FloatField(default=0.0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="api.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("korean_word", models.CharField(max_length=100)),
                ("north_korean_word", models.CharField(max_length=100)),
                ("is_called", models.BooleanField(default=False)),
                ("is_correct", models.BooleanField(default=False)),
                ("is_collect", models.BooleanField(default=False)),
                ("accuracy", models.FloatField(default=0.0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="api.chapter",
                    ),
                ),
            ],
        ),
    ]
